[versions]

generative-ai = "0.9.0-1.1.0"
konfig = "0.17.1"
koog = "0.2.1"

burst = "2.5.0"
compose = "1.8.1"
compose-hotReload = "1.0.0-alpha10"
compose-lazyLayouts = "0.3.0"
compose-stylesheet = "0.0.3"
exposed = "0.61.0"
jvmTarget = "17"
koalaplot = "0.8.0"
kotlin = "2.1.21"
kotlinx-browser = "0.3"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.2"
kotlinx-serializationJson = "1.8.1"
ktor = "3.2.0"
materialWeb = "2.2.0"
multiplatform-settings = "1.3.0"
shoelace = "2.20.0"
slf4j = "2.0.17"
sqlite-jdbc = "3.50.1.0"

[libraries]

generativeAi = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "generative-ai" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }

compose-lazyLayouts = { module = "dev.opensavvy.compose.lazy:lazy-layouts", version.ref = "compose-lazyLayouts" }
compose-stylesheet = { module = "com.moriatsushi.compose.stylesheet:compose-stylesheet", version.ref = "compose-stylesheet" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serializationJson" }
ktor-clientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-clientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-clientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-clientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-clientWasm = { module = "io.ktor:ktor-client-js-wasm-js", version.ref = "ktor" }
ktor-serializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
burst = { id = "app.cash.burst", version.ref = "burst" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
konfig = { id = "com.codingfeline.buildkonfig", version.ref = "konfig" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
